EES.MvcUI/Areas/Admin/Controllers/SystemModeController.cs
using System;
using System.Web.Mvc;
using System.Web.Routing;
using Ninject;
 
using EES.Entities.Concrete;
         
using EES.Business.Abstract;
         
using EES.MvcUI.Areas.Admin.Infrastructure;
         
using EES.MvcUI.Areas.Admin.Models.SystemModeModels;
        namespace EES.MvcUI.Areas.Admin.Controllers
{
    public class SystemModeController : AdminController
    {
        private readonly ISystemModeService _systemmodeService;

        public SystemModeController(ISystemModeService systemmodeService)
        {
            this._systemmodeService = systemmodeService;
        }

        //[ChildActionOnly]
        public ActionResult List()
        {
            var systemmode = _systemmodeService.GetAll();

            return DataTableContent(systemmode);
        }

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Create()
        {
            var model = new SystemModeSaveViewModel
            {
                SystemMode = new SystemMode()
            };

            return View("Save",model);
        }

        [HttpPost,ValidateAntiForgeryToken]
        public ActionResult Create(SystemMode systemMode)
        {
            _systemmodeService.Insert(systemMode);

            SuccessNotification("The item has been added");

            return RedirectToAction("Index");
        }

        public ActionResult Edit(int modeId)
        {
            var model = new SystemModeSaveViewModel
            {
                SystemMode = _systemmodeService.GetById(modeId)
            };

            return View("Save", model);
        }

        [HttpPost, ValidateAntiForgeryToken]
        public ActionResult Edit(SystemMode systemMode)
        {
            _systemmodeService.Update(systemMode);

            SuccessNotification("The item has been updated");

            return RedirectToAction("Index");
        }

        public ActionResult Delete(int modeId)
        {
            _systemmodeService.Delete(modeId);

            SuccessNotification("The item has been deleted");

            return RedirectToAction("Index");
        }
    }
}

EES.MvcUI/Areas/Admin/Views/SystemMode/Index.cshtml
@{
    ViewBag.Title = "SystemMode List";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<section class="content-header">
    <h1>
        SystemMode
        <small>SystemMode List</small>

        <a href="@Url.Action("Create","SystemMode",new{area="Admin"})" class="btn btn-xs btn-primary pull-right">
            <i class="glyphicon glyphicon-plus"></i> Add New SystemMode
        </a>
    </h1>
</section>
<section class="content">
    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                @*<div class="box-header">
                        <h3 class="box-title">Data Table With Full Features</h3>
                    </div>*@
                <!-- /.box-header -->
                <div class="box-body">
                    <table id="tblSystemMode" class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                 
                                <th>ModeId</th> 
                                 
                                <th>ModeName</th> 
                                 
                                <th>IsCurrentSystemMode</th> 
                                 
                                <th data-orderable="false"></th>
                            </tr>
                        </thead>
                    </table>
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
        </div>
        <!-- /.col -->
    </div>
</section>

@section scripts{
    <script>
        $(function () {
            $('#tblSystemMode').DataTable({
                "processing": true,
                "ajax": '@Url.Action("List","SystemMode",new{area="Admin"})',
                "deferRender": true,
                "columns": [
                     
                    { "data": "ModeId" },
                     
                    { "data": "ModeName" },
                     
                    { "data": "IsCurrentSystemMode" },
                     
                    {
                        "class": "text-center",
                        render: function (data, type, row) {
                            return '<a class="btn btn-xs btn-info btn-flat" href="@Url.Action("Edit","SystemMode",new{area="Admin"})?modeId='+row.ModeId+'">Edit</a> ' +
                                   '<a class="btn btn-xs btn-danger btn-flat" href="@Url.Action("Delete","SystemMode",new{area="Admin"})?modeId='+row.ModeId+'">Delete</a>';
                        }
                    }
                ]
            });
        });
    </script>
}

EES.MvcUI/Areas/Admin/Views/SystemMode/Save.cshtml
@model SystemModeSaveViewModel

@{
    ViewBag.Title = "SystemMode Save";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}


<section class="content-header">
    <h1>
        SystemMode Save
        <small>
            <a href="@Url.Action("Index","SystemMode",new{area="Admin"})">
                <i class="glyphicon glyphicon-chevron-left"></i> Back to SystemMode List
            </a>
        </small>
    </h1>
</section>
<section class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="box box-primary">
                @*<div class="box-header with-border">
                        <h3 class="box-title">Quick Example</h3>
                    </div>*@
                @using (Html.BeginForm(null, null, FormMethod.Post, new { @class = "form-horizontal" }))
                {
                    @Html.AntiForgeryToken()
                    <div class="box-body">
                     

                             
                                 @Html.HiddenFor(t=>t.SystemMode.ModeId)
                                          

                     

                            
                                <div class="form-group">
                                    @Html.LabelFor(t => t.SystemMode.ModeName, "ModeName", new { @class = "col-sm-2 control-label" })
                                    <div class="col-sm-10">
                                                                                @Html.TextBoxFor(t => t.SystemMode.ModeName, new { @class = "form-control"})
                                                                                @Html.ValidationMessageFor(t=>t.SystemMode.ModeName)
                                    </div>
                                </div>
                                          

                     

                            
                                <div class="form-group">
                                    <div class="col-sm-offset-2 col-sm-10">
                                        <div class="checkbox">
                                            <label>
                                                @Html.CheckBoxFor(t=>t.SystemMode.IsCurrentSystemMode) IsCurrentSystemMode
                                            </label>
                                        </div>
                                    </div>
                                </div>
                                          

                     
                    </div>
                    <div class="box-footer">
                        <button type="submit" class="btn btn-info btn-flat pull-right">Save</button>
                    </div>
                }
            </div>

        </div>
    </div>
</section>