EES.MvcUI/Areas/Admin/Controllers/EmployeeProjectController.cs
using System;
using System.Web.Mvc;
using System.Web.Routing;
using Ninject;
 
using EES.Entities.Concrete;
         
using EES.Business.Abstract;
         
using EES.MvcUI.Areas.Admin.Infrastructure;
         
using EES.MvcUI.Areas.Admin.Models.EmployeeProjectModels;
        namespace EES.MvcUI.Areas.Admin.Controllers
{
    public class EmployeeProjectController : AdminController
    {
        private readonly IEmployeeProjectService _employeeprojectService;

        public EmployeeProjectController(IEmployeeProjectService employeeprojectService)
        {
            this._employeeprojectService = employeeprojectService;
        }

        //[ChildActionOnly]
        public ActionResult List()
        {
            var employeeproject = _employeeprojectService.GetAll();

            return DataTableContent(employeeproject);
        }

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Create()
        {
            var model = new EmployeeProjectSaveViewModel
            {
                EmployeeProject = new EmployeeProject()
            };

            return View("Save",model);
        }

        [HttpPost,ValidateAntiForgeryToken]
        public ActionResult Create(EmployeeProject employeeProject)
        {
            _employeeprojectService.Insert(employeeProject);

            SuccessNotification("The item has been added");

            return RedirectToAction("Index");
        }

        public ActionResult Edit(int employeeProjectId)
        {
            var model = new EmployeeProjectSaveViewModel
            {
                EmployeeProject = _employeeprojectService.GetById(employeeProjectId)
            };

            return View("Save", model);
        }

        [HttpPost, ValidateAntiForgeryToken]
        public ActionResult Edit(EmployeeProject employeeProject)
        {
            _employeeprojectService.Update(employeeProject);

            SuccessNotification("The item has been updated");

            return RedirectToAction("Index");
        }

        public ActionResult Delete(int employeeProjectId)
        {
            _employeeprojectService.Delete(employeeProjectId);

            SuccessNotification("The item has been deleted");

            return RedirectToAction("Index");
        }
    }
}

EES.MvcUI/Areas/Admin/Views/EmployeeProject/Index.cshtml
@{
    ViewBag.Title = "EmployeeProject List";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<section class="content-header">
    <h1>
        EmployeeProject
        <small>EmployeeProject List</small>

        <a href="@Url.Action("Create","EmployeeProject",new{area="Admin"})" class="btn btn-xs btn-primary pull-right">
            <i class="glyphicon glyphicon-plus"></i> Add New EmployeeProject
        </a>
    </h1>
</section>
<section class="content">
    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                @*<div class="box-header">
                        <h3 class="box-title">Data Table With Full Features</h3>
                    </div>*@
                <!-- /.box-header -->
                <div class="box-body">
                    <table id="tblEmployeeProject" class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                 
                                <th>EmployeeProjectId</th> 
                                 
                                <th>EmployeeRoleId</th> 
                                 
                                <th>ProjectId</th> 
                                 
                                <th data-orderable="false"></th>
                            </tr>
                        </thead>
                    </table>
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
        </div>
        <!-- /.col -->
    </div>
</section>

@section scripts{
    <script>
        $(function () {
            $('#tblEmployeeProject').DataTable({
                "processing": true,
                "ajax": '@Url.Action("List","EmployeeProject",new{area="Admin"})',
                "deferRender": true,
                "columns": [
                     
                    { "data": "EmployeeProjectId" },
                     
                    { "data": "EmployeeRoleId" },
                     
                    { "data": "ProjectId" },
                     
                    {
                        "class": "text-center",
                        render: function (data, type, row) {
                            return '<a class="btn btn-xs btn-info btn-flat" href="@Url.Action("Edit","EmployeeProject",new{area="Admin"})?employeeProjectId='+row.EmployeeProjectId+'">Edit</a> ' +
                                   '<a class="btn btn-xs btn-danger btn-flat" href="@Url.Action("Delete","EmployeeProject",new{area="Admin"})?employeeProjectId='+row.EmployeeProjectId+'">Delete</a>';
                        }
                    }
                ]
            });
        });
    </script>
}

EES.MvcUI/Areas/Admin/Views/EmployeeProject/Save.cshtml
@model EmployeeProjectSaveViewModel

@{
    ViewBag.Title = "EmployeeProject Save";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}


<section class="content-header">
    <h1>
        EmployeeProject Save
        <small>
            <a href="@Url.Action("Index","EmployeeProject",new{area="Admin"})">
                <i class="glyphicon glyphicon-chevron-left"></i> Back to EmployeeProject List
            </a>
        </small>
    </h1>
</section>
<section class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="box box-primary">
                @*<div class="box-header with-border">
                        <h3 class="box-title">Quick Example</h3>
                    </div>*@
                @using (Html.BeginForm(null, null, FormMethod.Post, new { @class = "form-horizontal" }))
                {
                    @Html.AntiForgeryToken()
                    <div class="box-body">
                     

                             
                                 @Html.HiddenFor(t=>t.EmployeeProject.EmployeeProjectId)
                                          

                     

                            
                                <div class="form-group">
                                    @Html.LabelFor(t => t.EmployeeProject.EmployeeRoleId, "EmployeeRoleId", new { @class = "col-sm-2 control-label" })
                                    <div class="col-sm-10">
                                                                                @Html.EditorFor(t => t.EmployeeProject.EmployeeRoleId,"Number")
                                                                                @Html.ValidationMessageFor(t=>t.EmployeeProject.EmployeeRoleId)
                                    </div>
                                </div>
                                          

                     

                            
                                <div class="form-group">
                                    @Html.LabelFor(t => t.EmployeeProject.ProjectId, "ProjectId", new { @class = "col-sm-2 control-label" })
                                    <div class="col-sm-10">
                                                                                @Html.EditorFor(t => t.EmployeeProject.ProjectId,"Number")
                                                                                @Html.ValidationMessageFor(t=>t.EmployeeProject.ProjectId)
                                    </div>
                                </div>
                                          

                     
                    </div>
                    <div class="box-footer">
                        <button type="submit" class="btn btn-info btn-flat pull-right">Save</button>
                    </div>
                }
            </div>

        </div>
    </div>
</section>